"""Add refresh_token to users

Revision ID: 066baf6b4864
Revises: 5ea3ff3b0f92
Create Date: 2025-12-17 09:22:58.223638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066baf6b4864'
down_revision = '5ea3ff3b0f92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('refresh_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'refresh_token_expires')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
